windows-installer/setup.nsi
=> Check if browser is upgradeable for the current display before validating installed version

linux-installer/rvplayer-installer.sh, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg, windows-installer/setup.nsi
=> Update Player version

versions-config/remote-components-win.cfg, windows-installer/setup.nsi
=> Ignore DEMO displayId when checking if browser is upgradeable

versions-config/remote-components-win.cfg, windows-installer/Chromium.nsh, windows-installer/Java.nsh, windows-installer/RiseCache.nsh, windows-installer/RisePlayer.nsh, windows-installer/setup.nsi
=> Improve error handling on Windows installer

linux-installer/rvplayer-installer.sh, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg
=> Do not update components on Ubuntu 12.04 and 12.10

windows-installer/setup.nsi
=> Update installer version in NSIS' code

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Update Chrome to v46.0.2490.80 in *latest* channel and set rollout percent to 5

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Raise LatestRolloutPercent to 30 (Chrome 46 upgrade)

linux-installer/rvplayer-installer.sh
@fjvallarino I'm not sure how the existing installs are upgrading without prompting for user input.  Doesn't it look like this is necessary?
=> Call silent mode after upgrade

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Upgrade to Chrome 47.0.2526.80

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
Update the linux config files to represent reality
Update windows to set 0 percent upgrade as on linux
=> Update cfg files

windows-installer/setup.nsi
=> Do not stay on latest if stable and latest match; follow the standard procedure with probability check

linux-installer/rvplayer-installer.sh, windows-installer/setup.nsi
=> Apply rollout logic to installer upgrade

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-64.cfg, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Release latest version of RiseCache with 5% rollout (fixes deadlock issue and memory usage)

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Upgrade RisePlayer (restart external logging) and RiseCache (add User-Agent headers)

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Stop Player/Cache rollout for Installer v2

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json
=> Stop Player/Cache rollout for Installer v3

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Resume rollout of Player/Cache

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Raise rollout to 25% for Player/Cache releases. Also affects Chrome 47.

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Set rollout to 50pct

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
@ahmedalsudani @fjvallarino Please review
=> Update v2 installers to 100% chrome 47

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
@fjvallarino @ahmedalsudani Please review
=> Update rollout to ten percent

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
@fjvallarino @ahmedalsudani Please review
=> Update rollout to 50pct

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Set rollout to 20% for installer/player rollout

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
@fjvallarino @ahmedalsudani please review
=> Update installer and player

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json
@ahmedalsudani @fjvallarino please review.  I'll be setting these config files as well as putting the old EXE and SH files back into the main bucket dir.
=> Back to 2016.2.24.17.21

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json, versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Update rollout to 50

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json
@ahmedalsudani @fjvallarino please review for deployment.
=> Update electron installer version and rollout%

versions-config/electron-remote-components-lnx-32.cfg, versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.cfg, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.cfg, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.cfg, versions-config/electron-remote-components-win-64.json
@ahmedalsudani @fjvallarino for review
=> Rollout to ten percent

versions-config/electron-remote-components-win-32.json
=> Prevent upgrades on win32

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-64.json
=> Set 50% rollout for all but win32

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
@fjvallarino @ahmedalsudani please review.
=> Set BundleURL so upgrades can be tested

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
@ahmedalsudani @fjvallarino new bundle update.
=> Update bundle location

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Update bundle url

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Bump to 10%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Update rollout to 50%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Set installer rollout to 100%

versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Upgrade Chrome to 49.0.2623.110 on Latest channel and set 2% rollout

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Set cache rollout for v2 and v3

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Rollout 10pct

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Set rollout to 100%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
@fjvallarino whenever we're ready
=> Move to 2016.04.12.17.49 at 2%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Move to 35%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Rollout to 100%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Rollout release 9 at 2%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Release 10 at 1pct

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Release 10 to 5%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Release 10 to 20%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Release 10 to 100%

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Upgrade to Chrome 50 and RiseCache 2016.04.15.12.00 at 2% rollout

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Change Player version to make gradual rollout possible

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Start Release 11 at 2%

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Bump rollout percent to 10% for V2

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Rollout v3 at 5%

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Bump rollout percent to 50% for V2

versions-config/remote-components-lnx-32.cfg, versions-config/remote-components-lnx-64.cfg, versions-config/remote-components-win.cfg
=> Bump rollout for V2 to 100%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Set v3 to 20% rollout

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Set v3 to 100%

versions-config/electron-remote-components-lnx-32.json, versions-config/electron-remote-components-lnx-64.json, versions-config/electron-remote-components-win-32.json, versions-config/electron-remote-components-win-64.json
=> Release 12 1%
